# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Build steps go here..."

- stage: Deploy
  jobs:
  - deployment: DeploymentJob
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Pre-deployment steps go here..."
          - script: echo "Deployment steps go here..."
          - script: echo "Post-deployment steps go here..."
          - script: |
              curl -X POST \
              -H "Authorization: token $(GITHUB_TOKEN)" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/BiblioNexusStudio/aquifer-web/deployments \
              -d '{
                "ref": "$(Build.SourceVersion)",
                "task": "deploy",
                "environment": "dev",
                "auto_merge": false,
                "payload": {
                  "url": "https://google.com"
                },
                "state": "success",
                "description": "Deployed via Azure Pipelines"
              }'
            displayName: 'Create GitHub Deployment'
