# azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Replace 'main' with your main branch name

pr: none  # Disable CI builds for pull requests

pool:
  vmImage: 'ubuntu-latest'  # Choose the appropriate agent image

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Ensure Node.js 14 or later version is installed
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install Dependencies'

- script: |
    yarn run build
  displayName: 'Build SvelteKit Application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'  # The location of the build output
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'  # Archive the build artifacts
    replaceExistingArchive: true
  displayName: 'Archive Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'aquifer-web'
  displayName: 'Publish Build Artifacts'

# You can now add deployment steps below, depending on your deployment target.
# The following is an example for deploying to Azure Static Web Apps:

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    api_location: ''  # Leave this empty if you don't have Azure Functions
    output_location: ''  # Leave this empty to use the default
    azure_static_web_apps_api_token: $(AzureStaticWebAppsApiToken)  # Create an Azure DevOps variable group containing the API token for authentication

  # Add additional steps for post-deployment tasks if needed

