name: ' '
appendCommitMessageToRunName: true

resources:
    repositories:
        - repository: devops
          type: github
          name: BiblioNexusStudio/devops
          endpoint: BiblioNexusStudio
        - repository: aquifer_e2e
          type: github
          name: BiblioNexusStudio/aquifer-e2e
          endpoint: BiblioNexusStudio

pr: none
trigger:
    - master

pool:
    vmImage: ubuntu-latest

variables:
    - group: dev-web
    - group: qa-web
    - group: github-app

stages:
    - ${{ if contains(variables['Build.SourceVersionMessage'], '(#') }}:
        - stage: cleanup_qa_preview_env
          dependsOn: []
          jobs:
              - job: cleanup
                steps:
                    - template: templates/checkout_master.yml@devops
                    - template: templates/setup_node.yml@devops
                    - task: AzureCLI@2
                      inputs:
                          azureSubscription: dacfa945-984c-4708-9f2d-7d8358f223d5
                          scriptType: bash
                          scriptLocation: inlineScript
                          inlineScript: |
                              az staticwebapp environment delete \
                                  --yes --name aquifer-web-qa \
                                  --environment-name "pr$(echo $BUILD_SOURCEVERSIONMESSAGE | grep -oP '\(#\K\d+')"
                      displayName: Destroy preview environment in Azure
                    - script: |
                          $(Pipeline.Workspace)/devops/github-cli/script.sh deployment \
                              --privateKeyBase64 "$GITHUB_APP_PRIVATE_KEY_BASE64" \
                              --environment "pr$(echo $BUILD_SOURCEVERSIONMESSAGE | grep -oP '\(#\K\d+')" \
                              --destroy
                      env:
                          GITHUB_APP_PRIVATE_KEY_BASE64: $(GithubAppPrivateKeyBase64)
                      displayName: Destroy preview environment in GitHub

    - template: templates/setup_cache.yml

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: dev
          DependsOn: [setup_cache]
          AzureDevopsEnvName: dev-web
          CheckoutTemplate: templates/checkout_master.yml@devops
          CreateGithubRelease: true
          DeployApiToken: $(AzureStaticWebAppsApiTokenDev)
          DeployUrl: $(AzureStaticWebAppsDeployUrlDev)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: aquifer-web

    - template: templates/deploy_stage.yml
      parameters:
          DeployEnv: qa
          DependsOn: [setup_cache]
          AzureDevopsEnvName: qa-web
          CheckoutTemplate: templates/checkout_master.yml@devops
          DeployApiToken: $(AzureStaticWebAppsApiTokenQa)
          DeployUrl: $(AzureStaticWebAppsDeployUrlQa)
          GithubAppPrivateKeyBase64: $(GithubAppPrivateKeyBase64)
          SourceDirectory: aquifer-web

    - stage: e2e_tests
      dependsOn: [deploy_to_dev]
      jobs:
          - template: azure-devops/templates/e2e_tests.yml@aquifer_e2e
            parameters:
                Url: $(AzureStaticWebAppsDeployUrlDev)
