resources:
  pipelines:
  - pipeline: pre-merge-build
    source: aquifer-web-pre-merge
    branch: master
    trigger: true

pr: none
trigger: none

pool:
    vmImage: ubuntu-latest

stages:
    - stage: deploy_to_dev
      displayName: Deploy to dev
      jobs:
          - deployment: deploy_to_dev
            displayName: Deploy
            environment: dev
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/checkout.yml
                            - download: pre-merge-build
                              artifact: build
                              displayName: Download artifact
                            - script: cp ./src/env/dev-config.json $(Pipeline.Workspace)/pre-merge-build/build/env-config.json
                              displayName: Setup env
                            - script: cp staticwebapp.config.json $(Pipeline.Workspace)/pre-merge-build/build
                              displayName: Setup Azure config
                            - task: AzureStaticWebApp@0
                              inputs:
                                  cwd: $(Pipeline.Workspace)
                                  skip_app_build: true
                                  app_location: ./build
                                  api_location: ''
                                  production_branch: master
                                  output_location: ''
                                  azure_static_web_apps_api_token: $(AzureStaticWebAppsApiToken)
                              displayName: Deploy Azure Static Web App
