# make the name of the pipeline relevant and associated with the pull request
name: $[ format('PR {0} (build {1})', variables['System.PullRequest.PullRequestNumber'], counter(format('build{0}', variables['System.PullRequest.PullRequestNumber']), 1)) ]
appendCommitMessageToRunName: false

pr:
    branches:
        include:
            - '*'

trigger: none

pool:
    vmImage: ubuntu-latest

stages:
    - stage: test_and_build
      displayName: Test and build
      jobs:
          - job: lint_and_test
            displayName: Lint and test
            steps:
                - template: templates/checkout_pr.yml
                - template: templates/install_deps.yml
                - script: yarn lint:ci
                  displayName: ESLint
                - script: yarn test
                  displayName: Test

          - job: build
            displayName: Build
            dependsOn: lint_and_test
            steps:
                - template: templates/checkout_pr.yml
                - template: templates/install_deps.yml
                - template: templates/build_and_publish_artifact.yml
