pr:
    branches:
      include:
      - '*'

trigger: none

pool:
    vmImage: ubuntu-latest

jobs:
    - job: lint_and_test
      displayName: Lint and test
      steps:
          - template: templates/checkout_and_install_deps.yml
          - script: yarn lint:ci
            displayName: ESLint
          - script: yarn test
            displayName: Test

    - job: build
      displayName: Build
      dependsOn: lint_and_test
      steps:
          - template: templates/checkout_and_install_deps.yml
          - script: yarn build
            displayName: Build
          - script: zip -r build.zip build
            displayName: Zip artifact
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: build.zip
              artifactName: aquifer-web
            displayName: Publish artifact

