# make the name of the pipeline relevant and associated with the pull request
name: $[ format('PR {0} (deploy {1})', replace(replace(variables['Build.SourceBranch'], 'refs/pull/', ''), '/merge', ''), counter(format('deploy{0}', replace(replace(variables['Build.SourceBranch'], 'refs/pull/', ''), '/merge', '')), 1)) ]
appendCommitMessageToRunName: false

resources:
    pipelines:
        - pipeline: pre-merge-build
          source: aquifer-web-pre-merge
          branch: master-test
          trigger:
              branches:
                  include:
                      - refs/pull/*

pr: none
trigger: none

pool:
    vmImage: ubuntu-latest

stages:
    - stage: deploy_to_dev
      displayName: Deploy to dev
      dependsOn: []
      jobs:
          - deployment: deploy_to_dev
            displayName: Deploy to dev
            environment: dev-web
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/checkout_pr.yml
                            - download: pre-merge-build
                              artifact: build
                              displayName: Download artifact
                            - template: templates/deploy.yml
                              parameters:
                                DeployEnv: dev
                                ArtifactDir: $(Pipeline.Workspace)/pre-merge-build
                                DeployApiToken: $(AzureStaticWebAppsApiTokenDev)


    - stage: deploy_to_qa
      displayName: Deploy to qa (preview)
      dependsOn: []
      jobs:
          - deployment: deploy_to_qa
            displayName: Deploy to qa (preview)
            environment: qa-web-preview
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - template: templates/checkout_pr.yml
                            - download: pre-merge-build
                              artifact: build
                              displayName: Download artifact
                            - script: echo "##vso[task.setvariable variable=DeployPreviewName]pr$(echo $BUILD_SOURCEBRANCH | grep -oP "refs/pull/\K[0-9]+")"
                              displayName: Calculate deploy preview name
                            - template: templates/deploy.yml
                              parameters:
                                DeployEnv: qa
                                ArtifactDir: $(Pipeline.Workspace)/pre-merge-build
                                DeployApiToken: $(AzureStaticWebAppsApiTokenQa)
                                DeployPreviewName: $(DeployPreviewName)
