pr:
    branches:
      include:
      - '*'

trigger: none

pool:
    vmImage: ubuntu-latest

stages:
    - stage: test_and_build
      displayName: Test and build
      jobs:
          - job: lint_and_test
            displayName: Lint and test
            steps:
                - template: templates/checkout_and_install_deps.yml
                - script: yarn lint:ci
                  displayName: ESLint
                - script: yarn test
                  displayName: Test

          - job: build
            displayName: Build
            dependsOn: lint_and_test
            steps:
                - template: templates/checkout_and_install_deps.yml
                - script: yarn build
                  displayName: Build
                - publish: ./build
                  artifact: build
                  displayName: Publish artifact
