name: Deploy to env
description: Deploys to a specific environment. Assumes the source code has already been checked out.

inputs:
    environment:
        description: Environment to deploy to
        required: true
    api-token:
        description: API token for deployment
        required: true
    artifact-name:
        description: Name of artifact to deploy (artifact must be a zip file named `build.zip` containing a `build` directory)
        required: true
    force-pr-to-main-azure-environment:
        description: Specifies that even though running from a PR, the deployment should be on the main environment rather than a preview environment
        required: false
        default: false
    override-output-url:
        description: Overrides the output deployed-url
        required: false

outputs:
    deployed-url:
        description: The URL of the newly deployed app
        value: ${{ steps.calculate-url.outputs.url }}

runs:
    using: composite
    steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
              name: ${{ inputs.artifact-name }}
        - name: Unzip artifact
          run: unzip build.zip && rm build.zip
          shell: bash
        - name: Setup env
          run: cp src/env/${{ inputs.environment }}-config.json build/env-config.json
          shell: bash
        - name: Setup Azure config
          run: cp staticwebapp.config.json build/
          shell: bash
        - name: Maybe handle force-pr-to-main-azure-environment
          run: |
              if [[ "${{ inputs.force-pr-to-main-azure-environment }}" == "true" ]]; then
                  echo "DEPLOYMENT_PROVIDER=NotGithub" >> $GITHUB_ENV
                  echo "REPOSITORY_URL=${{ github.event.repository.html_url }}" >> $GITHUB_ENV
                  echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
              fi
          shell: bash
        - name: Deploy to Azure WebApp
          id: deploy-to-webapp
          uses: azure/static-web-apps-deploy@v1
          with:
              azure_static_web_apps_api_token: ${{ inputs.api-token }}
              skip_app_build: true
              skip_api_build: true
              action: upload
              app_location: build
              output_location: ''
        - name: Calculate URL
          id: calculate-url
          run: |
              if [[ -n "${{ inputs.override-output-url }}" ]]; then
                  echo "::set-output name=url::${{ inputs.override-output-url }}"
              else
                  echo "::set-output name=url::${{ steps.deploy-to-webapp.outputs.static_web_app_url }}"
              fi
          shell: bash
