name: Build and upload artifact
description: Builds the app and uploads as an artifact. Assumes the source code has already been checked out.

inputs:
    artifact-name:
        description: Name of artifact produced (contents is `build.zip` containing a `build` directory)
        required: true

runs:
    using: composite
    steps:
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 18.16.0
              cache: yarn
        - name: Install dependencies
          run: yarn install --frozen-lockfile
          shell: bash
        - name: Build
          run: yarn run build
          shell: bash
        - name: Zip artifact
          run: zip -r build.zip build
          shell: bash
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
              name: ${{ inputs.artifact-name }}
              path: build.zip
