interface resourceData {
    id: number;
    type: string;
    data: string | string[];
    downloaded: boolean;
    resourceSize?: number;
}

interface resouce {
    id: number;
    book: string;
    totalSize: number;
    chapter: number;
    resources: resourceData[];
    expanded?: boolean;
}

export const mockData: resouce[] = [
    {
        id: 1,
        book: '1 Timothy',
        totalSize: 506,
        chapter: 6,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1191,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1541,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: false,
                resourceSize: 1417,
            },
            {
                id: 4,
                type: 'video',
                data: 'path/to/video/file4.mp4',
                downloaded: true,
                resourceSize: 1073,
            },
        ],
    },
    {
        id: 2,
        book: 'Leviticus',
        totalSize: 1715,
        chapter: 46,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1921,
            },
        ],
    },
    {
        id: 3,
        book: '1 Chronicles',
        totalSize: 825,
        chapter: 18,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1750,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1643,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1128,
            },
        ],
    },
    {
        id: 4,
        book: '2 Corinthians',
        totalSize: 715,
        chapter: 18,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 536,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 503,
            },
        ],
    },
    {
        id: 5,
        book: 'Joel',
        totalSize: 1202,
        chapter: 40,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 992,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1461,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: true,
                resourceSize: 1055,
            },
            {
                id: 4,
                type: 'image',
                data: ['path/to/image/file4_1.jpg', 'path/to/image/file4_2.jpg'],
                downloaded: false,
                resourceSize: 1070,
            },
        ],
    },
    {
        id: 6,
        book: 'Ephesians',
        totalSize: 1029,
        chapter: 35,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1863,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1755,
            },
        ],
    },
    {
        id: 7,
        book: 'Daniel',
        totalSize: 1692,
        chapter: 6,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1087,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1089,
            },
        ],
    },
    {
        id: 8,
        book: 'Genesis',
        totalSize: 1709,
        chapter: 2,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1772,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 750,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: false,
                resourceSize: 1266,
            },
        ],
    },
    {
        id: 9,
        book: 'Romans',
        totalSize: 1532,
        chapter: 20,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1481,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1745,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1236,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1280,
            },
        ],
    },
    {
        id: 10,
        book: 'Habakkuk',
        totalSize: 1464,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1989,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 584,
            },
        ],
    },
    {
        id: 11,
        book: 'Exodus',
        totalSize: 819,
        chapter: 37,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 565,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1702,
            },
        ],
    },
    {
        id: 12,
        book: 'Zephaniah',
        totalSize: 615,
        chapter: 23,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1655,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 680,
            },
        ],
    },
    {
        id: 13,
        book: 'Zechariah',
        totalSize: 630,
        chapter: 13,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1811,
            },
        ],
    },
    {
        id: 14,
        book: 'Esther',
        totalSize: 1124,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 661,
            },
        ],
    },
    {
        id: 15,
        book: 'Lamentations',
        totalSize: 635,
        chapter: 49,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1226,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1160,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1207,
            },
            {
                id: 4,
                type: 'image',
                data: ['path/to/image/file4_1.jpg', 'path/to/image/file4_2.jpg'],
                downloaded: true,
                resourceSize: 606,
            },
        ],
    },
    {
        id: 16,
        book: 'James',
        totalSize: 755,
        chapter: 43,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 596,
            },
        ],
    },
    {
        id: 17,
        book: '1 Chronicles',
        totalSize: 683,
        chapter: 12,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1989,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 513,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1306,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1516,
            },
        ],
    },
    {
        id: 18,
        book: 'Hosea',
        totalSize: 588,
        chapter: 46,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 690,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 584,
            },
        ],
    },
    {
        id: 19,
        book: 'Colossians',
        totalSize: 1806,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1118,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1990,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 904,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: false,
                resourceSize: 1526,
            },
        ],
    },
    {
        id: 20,
        book: 'Isaiah',
        totalSize: 1471,
        chapter: 21,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1070,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1122,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 1327,
            },
        ],
    },
    {
        id: 21,
        book: '2 Thessalonians',
        totalSize: 1491,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1444,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1900,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1207,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 895,
            },
        ],
    },
    {
        id: 22,
        book: 'Jonah',
        totalSize: 1497,
        chapter: 8,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 637,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: false,
                resourceSize: 1282,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1878,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: false,
                resourceSize: 1787,
            },
        ],
    },
    {
        id: 23,
        book: '3 John',
        totalSize: 1953,
        chapter: 2,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1791,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 1122,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1897,
            },
        ],
    },
    {
        id: 24,
        book: '2 Corinthians',
        totalSize: 700,
        chapter: 30,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1421,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1113,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1263,
            },
            {
                id: 4,
                type: 'video',
                data: 'path/to/video/file4.mp4',
                downloaded: true,
                resourceSize: 1888,
            },
        ],
    },
    {
        id: 25,
        book: '2 Kings',
        totalSize: 878,
        chapter: 39,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1233,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 713,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 1932,
            },
        ],
    },
    {
        id: 26,
        book: 'Zechariah',
        totalSize: 1463,
        chapter: 28,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 814,
            },
        ],
    },
    {
        id: 27,
        book: 'Job',
        totalSize: 1605,
        chapter: 50,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1094,
            },
        ],
    },
    {
        id: 28,
        book: 'Job',
        totalSize: 1263,
        chapter: 31,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1838,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1605,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1438,
            },
        ],
    },
    {
        id: 29,
        book: 'Esther',
        totalSize: 1618,
        chapter: 34,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1210,
            },
        ],
    },
    {
        id: 30,
        book: '2 Corinthians',
        totalSize: 1988,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1203,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: false,
                resourceSize: 1253,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 831,
            },
        ],
    },
    {
        id: 31,
        book: '2 Kings',
        totalSize: 1305,
        chapter: 25,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1857,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 927,
            },
        ],
    },
    {
        id: 32,
        book: 'Song of Solomon',
        totalSize: 1225,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 970,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1610,
            },
        ],
    },
    {
        id: 33,
        book: 'Titus',
        totalSize: 1821,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1336,
            },
        ],
    },
    {
        id: 34,
        book: 'Esther',
        totalSize: 1431,
        chapter: 50,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1760,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1949,
            },
        ],
    },
    {
        id: 35,
        book: 'Joshua',
        totalSize: 1285,
        chapter: 31,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1080,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1449,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1438,
            },
        ],
    },
    {
        id: 36,
        book: '1 Peter',
        totalSize: 1943,
        chapter: 47,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 701,
            },
        ],
    },
    {
        id: 37,
        book: '1 Peter',
        totalSize: 1953,
        chapter: 43,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1523,
            },
        ],
    },
    {
        id: 38,
        book: '1 Thessalonians',
        totalSize: 1337,
        chapter: 38,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 893,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 1265,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 661,
            },
        ],
    },
    {
        id: 39,
        book: 'Song of Solomon',
        totalSize: 1818,
        chapter: 34,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 919,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 890,
            },
        ],
    },
    {
        id: 40,
        book: 'Exodus',
        totalSize: 1658,
        chapter: 15,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 1454,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1085,
            },
        ],
    },
    {
        id: 41,
        book: 'Ezra',
        totalSize: 1284,
        chapter: 12,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1127,
            },
        ],
    },
    {
        id: 42,
        book: 'Zechariah',
        totalSize: 896,
        chapter: 22,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1083,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1143,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 836,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 558,
            },
        ],
    },
    {
        id: 43,
        book: 'Job',
        totalSize: 1002,
        chapter: 43,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1762,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1266,
            },
        ],
    },
    {
        id: 44,
        book: '1 Kings',
        totalSize: 1984,
        chapter: 23,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1726,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 768,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 590,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: true,
                resourceSize: 841,
            },
        ],
    },
    {
        id: 45,
        book: '1 Chronicles',
        totalSize: 837,
        chapter: 33,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1170,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1984,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: false,
                resourceSize: 848,
            },
        ],
    },
    {
        id: 46,
        book: '1 Timothy',
        totalSize: 948,
        chapter: 19,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1659,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1168,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1661,
            },
        ],
    },
    {
        id: 47,
        book: 'Philemon',
        totalSize: 1952,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1472,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1184,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1089,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1533,
            },
        ],
    },
    {
        id: 48,
        book: 'Judges',
        totalSize: 1583,
        chapter: 30,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 754,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 557,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 918,
            },
        ],
    },
    {
        id: 49,
        book: '1 Timothy',
        totalSize: 694,
        chapter: 4,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1311,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1733,
            },
        ],
    },
    {
        id: 50,
        book: 'Micah',
        totalSize: 1813,
        chapter: 33,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1782,
            },
        ],
    },
    {
        id: 51,
        book: 'Hosea',
        totalSize: 1418,
        chapter: 22,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 846,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1576,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1370,
            },
        ],
    },
    {
        id: 52,
        book: '2 Samuel',
        totalSize: 1312,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 621,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1978,
            },
        ],
    },
    {
        id: 53,
        book: 'Hosea',
        totalSize: 1716,
        chapter: 13,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1019,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 692,
            },
        ],
    },
    {
        id: 54,
        book: 'Luke',
        totalSize: 1156,
        chapter: 23,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1458,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1791,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: true,
                resourceSize: 1687,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: true,
                resourceSize: 934,
            },
        ],
    },
    {
        id: 55,
        book: 'Micah',
        totalSize: 1447,
        chapter: 23,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1294,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1748,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1486,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: false,
                resourceSize: 1817,
            },
        ],
    },
    {
        id: 56,
        book: 'Judges',
        totalSize: 1636,
        chapter: 28,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1929,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 1932,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 527,
            },
        ],
    },
    {
        id: 57,
        book: '2 Kings',
        totalSize: 1564,
        chapter: 7,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1795,
            },
        ],
    },
    {
        id: 58,
        book: 'Ruth',
        totalSize: 1742,
        chapter: 22,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 981,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1685,
            },
        ],
    },
    {
        id: 59,
        book: '2 Peter',
        totalSize: 1875,
        chapter: 46,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1335,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 914,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1314,
            },
        ],
    },
    {
        id: 60,
        book: 'Philemon',
        totalSize: 1583,
        chapter: 50,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1615,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1576,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1362,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 793,
            },
        ],
    },
    {
        id: 61,
        book: 'Daniel',
        totalSize: 754,
        chapter: 31,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 660,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1468,
            },
        ],
    },
    {
        id: 62,
        book: 'Ezra',
        totalSize: 509,
        chapter: 4,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1936,
            },
        ],
    },
    {
        id: 63,
        book: 'Jonah',
        totalSize: 1883,
        chapter: 22,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 994,
            },
        ],
    },
    {
        id: 64,
        book: '2 Timothy',
        totalSize: 1146,
        chapter: 23,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 968,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1518,
            },
        ],
    },
    {
        id: 65,
        book: 'Revelation',
        totalSize: 1280,
        chapter: 39,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 504,
            },
        ],
    },
    {
        id: 66,
        book: '2 John',
        totalSize: 1575,
        chapter: 44,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 762,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1191,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 931,
            },
        ],
    },
    {
        id: 67,
        book: 'Jeremiah',
        totalSize: 964,
        chapter: 47,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1112,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1925,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: true,
                resourceSize: 504,
            },
            {
                id: 4,
                type: 'image',
                data: ['path/to/image/file4_1.jpg', 'path/to/image/file4_2.jpg'],
                downloaded: true,
                resourceSize: 1236,
            },
        ],
    },
    {
        id: 68,
        book: 'Hebrews',
        totalSize: 715,
        chapter: 8,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 908,
            },
        ],
    },
    {
        id: 69,
        book: '1 Samuel',
        totalSize: 1326,
        chapter: 30,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 772,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 607,
            },
        ],
    },
    {
        id: 70,
        book: 'Daniel',
        totalSize: 602,
        chapter: 36,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 1910,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1013,
            },
        ],
    },
    {
        id: 71,
        book: 'Ezra',
        totalSize: 940,
        chapter: 15,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1041,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 924,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: false,
                resourceSize: 1781,
            },
        ],
    },
    {
        id: 72,
        book: 'Galatians',
        totalSize: 848,
        chapter: 9,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1051,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1620,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 550,
            },
            {
                id: 4,
                type: 'video',
                data: 'path/to/video/file4.mp4',
                downloaded: false,
                resourceSize: 1877,
            },
        ],
    },
    {
        id: 73,
        book: 'Micah',
        totalSize: 754,
        chapter: 39,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1043,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1481,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 615,
            },
        ],
    },
    {
        id: 74,
        book: 'Joel',
        totalSize: 738,
        chapter: 49,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1700,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1227,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: false,
                resourceSize: 1161,
            },
        ],
    },
    {
        id: 75,
        book: 'Nehemiah',
        totalSize: 954,
        chapter: 3,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 506,
            },
        ],
    },
    {
        id: 76,
        book: '1 Corinthians',
        totalSize: 528,
        chapter: 29,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1454,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1513,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 643,
            },
        ],
    },
    {
        id: 77,
        book: '1 Peter',
        totalSize: 1451,
        chapter: 24,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1005,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: false,
                resourceSize: 820,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 973,
            },
        ],
    },
    {
        id: 78,
        book: 'Habakkuk',
        totalSize: 1807,
        chapter: 17,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1561,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1502,
            },
        ],
    },
    {
        id: 79,
        book: '2 Samuel',
        totalSize: 1396,
        chapter: 16,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1790,
            },
        ],
    },
    {
        id: 80,
        book: '1 Peter',
        totalSize: 1135,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1661,
            },
        ],
    },
    {
        id: 81,
        book: 'Micah',
        totalSize: 1425,
        chapter: 18,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1137,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1282,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: false,
                resourceSize: 1370,
            },
        ],
    },
    {
        id: 82,
        book: 'Proverbs',
        totalSize: 1126,
        chapter: 10,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 837,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 656,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 769,
            },
        ],
    },
    {
        id: 83,
        book: 'Malachi',
        totalSize: 1360,
        chapter: 8,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1774,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1157,
            },
            {
                id: 3,
                type: 'image',
                data: ['path/to/image/file3_1.jpg', 'path/to/image/file3_2.jpg'],
                downloaded: true,
                resourceSize: 1340,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1091,
            },
        ],
    },
    {
        id: 84,
        book: 'Philippians',
        totalSize: 1315,
        chapter: 2,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1210,
            },
        ],
    },
    {
        id: 85,
        book: '2 Corinthians',
        totalSize: 953,
        chapter: 40,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: false,
                resourceSize: 1514,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1725,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1083,
            },
            {
                id: 4,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 961,
            },
        ],
    },
    {
        id: 86,
        book: 'Joel',
        totalSize: 617,
        chapter: 35,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 1870,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 639,
            },
        ],
    },
    {
        id: 87,
        book: '2 Corinthians',
        totalSize: 1082,
        chapter: 15,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1402,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1741,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: true,
                resourceSize: 840,
            },
        ],
    },
    {
        id: 88,
        book: 'Zechariah',
        totalSize: 573,
        chapter: 11,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 604,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1375,
            },
            {
                id: 3,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1613,
            },
            {
                id: 4,
                type: 'image',
                data: ['path/to/image/file4_1.jpg', 'path/to/image/file4_2.jpg'],
                downloaded: false,
                resourceSize: 605,
            },
        ],
    },
    {
        id: 89,
        book: '2 Peter',
        totalSize: 1912,
        chapter: 15,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 717,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1267,
            },
        ],
    },
    {
        id: 90,
        book: 'Job',
        totalSize: 801,
        chapter: 46,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 661,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1405,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 556,
            },
            {
                id: 4,
                type: 'audio',
                data: ['path/to/audio/file4_1.mp3', 'path/to/audio/file4_2.mp3'],
                downloaded: true,
                resourceSize: 850,
            },
        ],
    },
    {
        id: 91,
        book: 'Leviticus',
        totalSize: 1503,
        chapter: 44,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 622,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: true,
                resourceSize: 1704,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: false,
                resourceSize: 1671,
            },
            {
                id: 4,
                type: 'video',
                data: 'path/to/video/file4.mp4',
                downloaded: true,
                resourceSize: 1414,
            },
        ],
    },
    {
        id: 92,
        book: 'Deuteronomy',
        totalSize: 1222,
        chapter: 17,
        resources: [
            {
                id: 1,
                type: 'video',
                data: 'path/to/video/file1.mp4',
                downloaded: true,
                resourceSize: 1184,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1597,
            },
        ],
    },
    {
        id: 93,
        book: 'Genesis',
        totalSize: 1310,
        chapter: 48,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: true,
                resourceSize: 1707,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 972,
            },
        ],
    },
    {
        id: 94,
        book: '1 Corinthians',
        totalSize: 1889,
        chapter: 12,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 1904,
            },
            {
                id: 2,
                type: 'image',
                data: ['path/to/image/file2_1.jpg', 'path/to/image/file2_2.jpg'],
                downloaded: true,
                resourceSize: 1298,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1501,
            },
        ],
    },
    {
        id: 95,
        book: 'Exodus',
        totalSize: 1802,
        chapter: 41,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: false,
                resourceSize: 841,
            },
            {
                id: 2,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: true,
                resourceSize: 1268,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: false,
                resourceSize: 1335,
            },
        ],
    },
    {
        id: 96,
        book: 'Obadiah',
        totalSize: 1648,
        chapter: 38,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 1782,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: true,
                resourceSize: 1822,
            },
            {
                id: 3,
                type: 'audio',
                data: ['path/to/audio/file3_1.mp3', 'path/to/audio/file3_2.mp3'],
                downloaded: true,
                resourceSize: 961,
            },
        ],
    },
    {
        id: 97,
        book: 'Genesis',
        totalSize: 742,
        chapter: 13,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 1785,
            },
            {
                id: 2,
                type: 'video',
                data: 'path/to/video/file2.mp4',
                downloaded: false,
                resourceSize: 1820,
            },
            {
                id: 3,
                type: 'video',
                data: 'path/to/video/file3.mp4',
                downloaded: false,
                resourceSize: 1380,
            },
            {
                id: 4,
                type: 'image',
                data: ['path/to/image/file4_1.jpg', 'path/to/image/file4_2.jpg'],
                downloaded: false,
                resourceSize: 1344,
            },
        ],
    },
    {
        id: 98,
        book: 'Philemon',
        totalSize: 1903,
        chapter: 18,
        resources: [
            {
                id: 1,
                type: 'audio',
                data: ['path/to/audio/file1_1.mp3', 'path/to/audio/file1_2.mp3'],
                downloaded: true,
                resourceSize: 1062,
            },
        ],
    },
    {
        id: 99,
        book: '1 John',
        totalSize: 1318,
        chapter: 50,
        resources: [
            {
                id: 1,
                type: 'text',
                data: 'This is some sample text.',
                downloaded: false,
                resourceSize: 630,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 1166,
            },
        ],
    },
    {
        id: 100,
        book: 'Haggai',
        totalSize: 1546,
        chapter: 31,
        resources: [
            {
                id: 1,
                type: 'image',
                data: ['path/to/image/file1_1.jpg', 'path/to/image/file1_2.jpg'],
                downloaded: false,
                resourceSize: 759,
            },
            {
                id: 2,
                type: 'audio',
                data: ['path/to/audio/file2_1.mp3', 'path/to/audio/file2_2.mp3'],
                downloaded: false,
                resourceSize: 748,
            },
        ],
    },
];
