name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Zip artifact
        run: zip -r aquifer-web-build.zip build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aquifer-web-build
          path: aquifer-web-build.zip

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: ${{ steps.deploy-to-webapp.outputs.static_web_app_url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: aquifer-web-build
      - name: Unzip artifact
        run: unzip aquifer-web-build.zip && rm aquifer-web-build.zip
      - name: Deploy to Azure WebApp
        id: deploy-to-webapp
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          skip_app_build: true
          skip_api_build: true
          action: upload
          app_location: build
          output_location: ''

  e2e_tests:
    runs-on: ubuntu-latest
    needs: deploy_to_dev
    steps:
      - name: Checkout E2E test code
        uses: actions/checkout@v3
        with:
          repository: BiblioNexusStudio/aquifer-e2e
          ssh-key: ${{ secrets.AQUIFER_E2E_SSH_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn run test
