name: Pre-merge

on:
    pull_request:
        branches:
            - '**'

jobs:
    lint_and_test:
        name: Lint and test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.16.0
                  cache: yarn
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: ESLint
              run: yarn run lint:ci
            - name: Test
              run: yarn run test

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - uses: ./.github/actions/build-and-upload-artifact
              with:
                  artifact-name: aquifer-web-build

    # DISABLING THIS UNTIL WE CAN REQUIRE APPROVAL FOR DEPLOYS SO WE AREN'T ALWAYS OVERRIDING DEV

    deploy_to_dev:
        name: Deploy to dev
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: dev
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - uses: ./.github/actions/deploy-to-env
              id: deploy
              with:
                  environment: dev
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  artifact-name: aquifer-web-build
                  force-pr-to-main-azure-environment: true
                  override-output-url: https://polite-pond-08e447610.3.azurestaticapps.net/

    # This will deploy to a "preview environment" in Azure Static Web Apps
    # which means each PR will get its own environment. This means multiple PRs
    # can be tested at the same time.
    deploy_to_qa:
        name: Deploy to qa
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: qa
            url: ${{ steps.deploy.outputs.deployed-url }}
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - uses: ./.github/actions/deploy-to-env
              id: deploy
              with:
                  environment: qa
                  api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  artifact-name: aquifer-web-build
